sudo: required
language: python
services:
  - docker
before_install:
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - ./scripts/build.sh
script:
  - ./scripts/test.sh
