# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20180319_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
